name: Rust Clippy

on: [push]
    
env:
    CARGO_TERM_COLOR: always

jobs:
    run_clippy:
        name: Debug Build Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Clippy
          run: cargo clippy

    run_clippy_release:
        name: Release Build Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Clippy
          run: cargo clippy --release